In [1]:
import os
import pandas as pd

In [2]:
# Path setup
BASE_PATH = os.path.abspath(os.path.join(os.getcwd(), ".."))
DATASET_PATH = os.path.join(BASE_PATH, "data", "raw")

print("Dataset Path:", DATASET_PATH)

Dataset Path: d:\VIT Personal\TrustFilterAI\ml\counterfeit_detection\data\raw

In [3]:
# Load dataset 
classes = ["genuine", "fake"]
data = []

for brand in os.listdir(DATASET_PATH):
    brand_path = os.path.join(DATASET_PATH, brand)
    
    if not os.path.isdir(brand_path):
        continue
    
    for label in classes:
        label_path = os.path.join(brand_path, label)
        
        if not os.path.exists(label_path):
            continue
        
        for img_name in os.listdir(label_path):
            img_path = os.path.join(label_path, img_name)
            
            data.append({
                "image_path": img_path,
                "label": label,
                "brand": brand
            })

df = pd.DataFrame(data)
df.head()

                                          image_path    label            brand
0  d:\VIT Personal\TrustFilterAI\ml\counterfeit_d...  genuine  Audemars Piguet
1  d:\VIT Personal\TrustFilterAI\ml\counterfeit_d...  genuine  Audemars Piguet
2  d:\VIT Personal\TrustFilterAI\ml\counterfeit_d...  genuine  Audemars Piguet
3  d:\VIT Personal\TrustFilterAI\ml\counterfeit_d...  genuine  Audemars Piguet
4  d:\VIT Personal\TrustFilterAI\ml\counterfeit_d...  genuine  Audemars Piguet

In [4]:
print("Total Images:", len(df))

print("\nClass Distribution:")
print(df["label"].value_counts())

print("\nBrand Distribution:")
print(df["brand"].value_counts())

Total Images: 4000

Class Distribution:
label
genuine    2000
fake       2000
Name: count, dtype: int64

Brand Distribution:
brand
Audemars Piguet        400
Breguet                400
Breitling              400
Maurice Lacroix        400
Omega                  400
Patek Philippe         400
Rado                   400
Rolex                  400
Tissot                 400
Vacheron Constantin    400
Name: count, dtype: int64

In [5]:
# Map labels to numeric values
label_map = {"genuine": 0, "fake": 1}
df["label_num"] = df["label"].map(label_map)

df.head()

,image_path,label,brand,label_num
0,d:\VIT Personal\TrustFilterAI\ml\counterfeit_d...,genuine,Audemars Piguet,0
1,d:\VIT Personal\TrustFilterAI\ml\counterfeit_d...,genuine,Audemars Piguet,0
2,d:\VIT Personal\TrustFilterAI\ml\counterfeit_d...,genuine,Audemars Piguet,0
3,d:\VIT Personal\TrustFilterAI\ml\counterfeit_d...,genuine,Audemars Piguet,0
4,d:\VIT Personal\TrustFilterAI\ml\counterfeit_d...,genuine,Audemars Piguet,0

In [6]:
# Save the processed dataset to a CSV file
output_path = os.path.join(BASE_PATH, "data", "processed", "dataset.csv")

os.makedirs(os.path.dirname(output_path), exist_ok=True)

df.to_csv(output_path, index=False)

print("Saved dataset to:", output_path)

Saved dataset to: d:\VIT Personal\TrustFilterAI\ml\counterfeit_detection\data\processed\dataset.csv